# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-09 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HostList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_host_id', models.IntegerField(default=0, verbose_name='ServerID')),
                ('f_host_domain', models.CharField(max_length=50, verbose_name='\u57df\u540d')),
                ('f_host_lan', models.CharField(max_length=50, verbose_name='IP\u5730\u5740')),
                ('f_host_wan', models.CharField(max_length=50, verbose_name='wan_IP\u5730\u5740')),
                ('f_host_port', models.IntegerField(default='22', verbose_name='ssh')),
                ('f_host_pass', models.CharField(default='', max_length=20, verbose_name='\u5bc6\u7801')),
                ('host_context', models.TextField(default='', max_length=100, verbose_name='\u63cf\u8ff0\u4fe1\u606f')),
            ],
            options={
                'verbose_name': '\u4e3b\u673a\u4fe1\u606f',
                'verbose_name_plural': '\u4e3b\u673a\u4fe1\u606f',
            },
        ),
    ]
