# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-13 21:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0003_auto_20170309_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostlist',
            name='f_groups_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosts.GroupHost', verbose_name='\u5e73\u53f0ID'),
        ),
        migrations.AlterUniqueTogether(
            name='hostlist',
            unique_together=set([('f_host_id', 'f_host_domain')]),
        ),
    ]
